# Generated by Django 4.2.10 on 2025-08-07 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libraries', '0002_initial'),
        ('videos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='libraries.library')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('download_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('download_url', models.URLField(blank=True, max_length=500, null=True)),
                ('download_url_expiry', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='orders.order')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='videos.video')),
            ],
            options={
                'unique_together': {('order', 'video', 'resolution')},
            },
        ),
        migrations.CreateModel(
            name='DownloadRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email address to send download link to', max_length=254)),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', help_text='Status of the download request', max_length=20)),
                ('download_url', models.URLField(blank=True, help_text='S3 presigned URL for download', max_length=500, null=True)),
                ('expiry_date', models.DateTimeField(help_text='When the download link expires (48 hours from creation)')),
                ('email_sent', models.BooleanField(default=False, help_text='Whether the email has been sent')),
                ('email_sent_at', models.DateTimeField(blank=True, help_text='When the email was sent', null=True)),
                ('email_error', models.TextField(blank=True, help_text='Any error messages from email sending')),
                ('s3_key', models.CharField(blank=True, help_text='S3 key for the video file', max_length=500)),
                ('aws_request_id', models.CharField(blank=True, help_text='AWS request ID for tracking', max_length=100)),
                ('bulk_request_id', models.CharField(blank=True, help_text='ID to group related bulk download requests', max_length=100)),
                ('is_bulk_request', models.BooleanField(default=False, help_text='Whether this request is part of a bulk request')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_requests', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_requests', to='videos.video')),
            ],
            options={
                'ordering': ['-request_date'],
                'indexes': [models.Index(fields=['user', 'status'], name='orders_down_user_id_f3dbb9_idx'), models.Index(fields=['expiry_date'], name='orders_down_expiry__32d24f_idx'), models.Index(fields=['status', 'expiry_date'], name='orders_down_status_78fa88_idx')],
            },
        ),
    ]
