# Generated by Django 4.2.10 on 2025-04-02 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='library_logos/')),
                ('color_scheme', models.JSONField(blank=True, default=dict)),
                ('storage_tier', models.CharField(choices=[('basic', 'Basic'), ('pro', 'Professional'), ('enterprise', 'Enterprise')], default='basic', max_length=20)),
                ('storage_limit', models.PositiveIntegerField(default=107374182400)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_libraries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Libraries',
            },
        ),
        migrations.CreateModel(
            name='UserLibraryRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('contributor', 'Contributor')], max_length=20)),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='libraries.library')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Library Roles',
            },
        ),
    ]
