# Generated by Django 4.2.10 on 2025-04-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libraries', '0001_initial'),
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='libraries', to='videos.video'),
        ),
        migrations.AlterUniqueTogether(
            name='userlibraryrole',
            unique_together={('library', 'user')},
        ),
    ]
