# Generated by Django 4.2.10 on 2025-03-31 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
