# Generated by Django 4.2.10 on 2025-04-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='storage_limit',
        ),
        migrations.AddField(
            model_name='library',
            name='storage_size',
            field=models.BigIntegerField(default=107374182400),
        ),
    ]
