# Generated by Django 4.2.10 on 2025-07-05 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0004_alter_library_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='category_source',
            field=models.CharField(choices=[('paletta_style', 'Use Paletta Style Categories'), ('custom', 'Create My Own Categories')], default='custom', help_text='Choose the source for video categories in this library', max_length=20),
        ),
    ]
