# Generated by Django 4.2.10 on 2025-04-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='tags',
            field=models.ManyToManyField(related_name='videos', through='videos.VideoTag', to='videos.tag'),
        ),
    ]
