# Generated by Django 4.2.10 on 2025-06-15 14:26

from django.db import migrations, models
import paletta_core.storage
import videos.models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='is_published',
        ),
        migrations.AddField(
            model_name='video',
            name='format',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='frame_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Frame rate, e.g., 29.97', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='resolution',
            field=models.CharField(blank=True, help_text='Video resolution, e.g., 1920x1080', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=paletta_core.storage.get_media_storage, upload_to=videos.models.category_image_path),
        ),
        migrations.AlterField(
            model_name='video',
            name='storage_reference_id',
            field=models.CharField(blank=True, help_text='Reference ID in the AWS S3 storage system', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='storage_status',
            field=models.CharField(choices=[('pending', 'Pending Upload'), ('uploading', 'Uploading to Storage'), ('stored', 'Stored in Deep Storage'), ('failed', 'Upload Failed'), ('processing', 'Processing'), ('processing_failed', 'Processing Failed')], default='pending', help_text='Current status of the video in AWS S3 storage', max_length=20),
        ),
        migrations.AlterField(
            model_name='video',
            name='storage_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, storage=paletta_core.storage.get_media_storage, upload_to=videos.models.thumbnail_upload_path),
        ),
    ]
