# Generated by Django 5.1.6 on 2025-03-10 17:34

import videos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_duration_video_file_size_video_is_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image for this category. Recommended size: 200x200px.', null=True, upload_to=videos.models.category_image_path),
        ),
    ]
