# Generated by Django 4.2.10 on 2025-03-11 12:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import videos.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0003_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='download_link',
            field=models.URLField(blank=True, help_text='Temporary download link for the video', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='download_link_expiry',
            field=models.DateTimeField(blank=True, help_text='Expiration time for the download link', null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='storage_reference_id',
            field=models.CharField(blank=True, help_text='Reference ID in the AWS S3 storage system', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='storage_status',
            field=models.CharField(choices=[('pending', 'Pending Upload'), ('uploading', 'Uploading to Storage'), ('stored', 'Stored in Deep Storage'), ('failed', 'Upload Failed'), ('processing', 'Processing')], default='pending', help_text='Current status of the video in AWS S3 storage', max_length=20),
        ),
        migrations.AddField(
            model_name='video',
            name='storage_url',
            field=models.URLField(blank=True, help_text='URL to the video in AWS S3 storage', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, help_text='Temporary storage before uploading to AWS S3 storage', null=True, upload_to=videos.models.video_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'wmv', 'flv', 'mkv'])]),
        ),
        migrations.CreateModel(
            name='VideoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('log_type', models.CharField(choices=[('upload', 'Video Uploaded'), ('process', 'Video Processing'), ('store', 'Video Stored in S3'), ('download', 'Video Download Requested'), ('delete', 'Video Deleted'), ('error', 'Error Occurred'), ('status_change', 'Status Changed')], max_length=20)),
                ('message', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='Size in bytes', null=True)),
                ('storage_status', models.CharField(blank=True, max_length=20, null=True)),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_logs', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='videos.video')),
            ],
            options={
                'verbose_name': 'Video Log',
                'verbose_name_plural': 'Video Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
