# Generated by Django 4.2.10 on 2025-06-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_remove_video_is_published_video_format_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['subject_area', 'content_type'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='content_type',
            field=models.CharField(blank=True, choices=[('campus_life', 'Campus Life'), ('teaching_learning', 'Teaching & Learning'), ('research_innovation', 'Research & Innovation'), ('city_environment', 'City & Environment'), ('aerial_establishing', 'Aerial & Establishing Shots'), ('people_portraits', 'People & Portraits'), ('culture_events', 'Culture & Events'), ('workspaces_facilities', 'Workspaces & Facilities'), ('cutaways_abstracts', 'Cutaways & Abstracts'), ('historical_archive', 'Historical & Archive')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this category is available for selection'),
        ),
        migrations.AddField(
            model_name='category',
            name='subject_area',
            field=models.CharField(blank=True, choices=[('engineering_sciences', 'Engineering Sciences'), ('mathematical_physical_sciences', 'Mathematical & Physical Sciences'), ('medical_sciences', 'Medical Sciences'), ('life_sciences', 'Life Sciences'), ('brain_sciences', 'Brain Sciences'), ('built_environment', 'Built Environment'), ('population_health', 'Population Health'), ('arts_humanities', 'Arts & Humanities'), ('social_historical_sciences', 'Social & Historical Sciences'), ('education', 'Education'), ('fine_art', 'Fine Art'), ('law', 'Law'), ('business', 'Business')], max_length=50, null=True),
        ),
    ]
