# Generated by Django 4.2.10 on 2025-07-05 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0005_library_category_source'),
        ('videos', '0004_alter_category_options_category_content_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('campus_life', 'Campus Life'), ('teaching_learning', 'Teaching & Learning'), ('research_innovation', 'Research & Innovation'), ('city_environment', 'City & Environment'), ('aerial_establishing', 'Aerial & Establishing Shots'), ('people_portraits', 'People & Portraits'), ('culture_events', 'Culture & Events'), ('workspaces_facilities', 'Workspaces & Facilities'), ('cutaways_abstracts', 'Cutaways & Abstracts'), ('historical_archive', 'Historical & Archive')], max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PalettaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('people_community', 'People and Community'), ('buildings_architecture', 'Buildings & Architecture'), ('classrooms_learning', 'Classrooms & Learning Spaces'), ('field_trips_outdoor', 'Field Trips & Outdoor Learning'), ('events_conferences', 'Events & Conferences'), ('research_innovation_spaces', 'Research & Innovation Spaces'), ('technology_equipment', 'Technology & Equipment'), ('everyday_campus', 'Everyday Campus Life'), ('urban_natural_environments', 'Urban & Natural Environments'), ('backgrounds_abstracts', 'Backgrounds & Abstracts'), ('private', 'Private')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Paletta Category',
                'verbose_name_plural': 'Paletta Categories',
                'ordering': ['code'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['subject_area', 'custom_name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='video',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='custom_name',
            field=models.CharField(blank=True, help_text="Custom category name (used when subject_area is 'custom')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='subject_area',
            field=models.ForeignKey(default='', help_text='Required: Select one subject area', on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='videos.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='subject_area',
            field=models.CharField(choices=[('private', 'Private'), ('custom', 'Custom'), ('engineering_sciences', 'Engineering Sciences'), ('mathematical_physical_sciences', 'Mathematical & Physical Sciences'), ('medical_sciences', 'Medical Sciences'), ('life_sciences', 'Life Sciences'), ('brain_sciences', 'Brain Sciences'), ('built_environment', 'Built Environment'), ('population_health', 'Population Health'), ('arts_humanities', 'Arts & Humanities'), ('social_historical_sciences', 'Social & Historical Sciences'), ('education', 'Education'), ('fine_art', 'Fine Art'), ('law', 'Law'), ('business', 'Business'), ('people_community', 'People and Community'), ('buildings_architecture', 'Buildings & Architecture'), ('classrooms_learning', 'Classrooms & Learning Spaces'), ('field_trips_outdoor', 'Field Trips & Outdoor Learning'), ('events_conferences', 'Events & Conferences'), ('research_innovation_spaces', 'Research & Innovation Spaces'), ('technology_equipment', 'Technology & Equipment'), ('everyday_campus', 'Everyday Campus Life'), ('urban_natural_environments', 'Urban & Natural Environments'), ('backgrounds_abstracts', 'Backgrounds & Abstracts')], default='unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('subject_area', 'library'), ('custom_name', 'library')},
        ),
        migrations.DeleteModel(
            name='Upload',
        ),
        migrations.RemoveField(
            model_name='category',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.AddField(
            model_name='video',
            name='content_types',
            field=models.ManyToManyField(help_text='Required: Select 1-3 content types', related_name='videos', to='videos.contenttype'),
        ),
        migrations.AddField(
            model_name='video',
            name='paletta_category',
            field=models.ForeignKey(blank=True, help_text='For Paletta library videos only', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='videos.palettacategory'),
        ),
    ]
